// This file is generated by gw2lfg-discord-bot.
// Manual edits may be overwritten while the bot is running.

const discordFeeds = [
  {
    "id": "feed-one",
    "title": "GW2 LFG Feed",
    "serverName": "GW2 LFG",
    "channelName": "meta-trains",
    "description": "Recent group-finder posts from this Discord channel.",
    "messages": [
      {
        "authorName": "Overflow Trading Company #︱🚂choo-choo-alerts",
        "content": "@[NA]TrainAlerts Twisted Marionette (Rerun) | eta start @ x:45\n`/sqjoin Lee Ming Wei` or via LFG (World Boss)\nPS: bcuz we had an oopsie",
        "timestamp": "2026-05-03T13:20:04.683Z",
        "jumpUrl": "https://discord.com/channels/1485058470775623793/1499526414439944222/1500487109818188030"
      },
      {
        "authorName": "Overflow Trading Company #︱🚂choo-choo-alerts",
        "content": "@[NA]TrainAlerts Twisted Marionette | forming up right now\n`/sqjoin Lee Ming Wei` or via LFG (World Boss)",
        "timestamp": "2026-05-03T12:23:00.280Z",
        "jumpUrl": "https://discord.com/channels/1485058470775623793/1499526414439944222/1500472746830991391"
      },
      {
        "authorName": "Overflow Trading Company #︱🚂choo-choo-alerts",
        "content": "@[NA]TrainAlerts KFC (escort) > Epooch\n`/sqjoin Lee Ming Wei` or via LFG (Inner Mayos)",
        "timestamp": "2026-05-03T11:24:32.589Z",
        "jumpUrl": "https://discord.com/channels/1485058470775623793/1499526414439944222/1500458034508464141"
      },
      {
        "authorName": "Overflow Trading Company #︱🚂choo-choo-alerts",
        "content": "@[NA]TrainAlerts \nSaturday Night SotO Convergence CM x5 squad is live.\nSlamming gold all bosses.\nBring POWER DPS builds so you can use demon slaying station and sigil.\nBring RELIC OF THE EAGLE for big dmg modifier for second half of fight.\n/sqjoin MarshAll.3528\nWe start as soon as we fill!",
        "timestamp": "2026-05-03T01:57:31.837Z",
        "jumpUrl": "https://discord.com/channels/1485058470775623793/1499526414439944222/1500315341132398695"
      },
      {
        "authorName": "Overflow Trading Company #︱🚂choo-choo-alerts",
        "content": "@[NA]TrainAlerts\nIt's Ratvergence (SotO CM Convergences) time!\n- Bring power builds if you can\n- Bring Sigil of Demon Slaying and Sigil of the Night if power\n- Bring Relic of the Eagle if power\n- Bring stacking sigils if applicable\n- Discord is _required_!\nMessage me in game with any questions!\n`/sqjoin lilyvelour`",
        "timestamp": "2026-05-02T22:40:53.222Z",
        "jumpUrl": "https://discord.com/channels/1485058470775623793/1499526414439944222/1500265854154309644"
      },
      {
        "authorName": "Overflow Trading Company #︱🚂choo-choo-alerts",
        "content": "@[NA]TrainAlerts Battle For Lions Arch (Private) -> Tower of Nightmares (Public)\n`/sqjoin Lee Ming Wei` or via LFG (World Bosses)",
        "timestamp": "2026-05-02T15:19:52.596Z",
        "jumpUrl": "https://discord.com/channels/1485058470775623793/1499526414439944222/1500154870244835483"
      },
      {
        "authorName": "Overflow Trading Company #︱🚂choo-choo-alerts",
        "content": "@[NA]TrainAlerts [AO] Path of Friday Meta Train!\nPtA/Doppel > Pinata > Serpents' Ire > Maws\n/sqjoin OverRealm.3542",
        "timestamp": "2026-05-02T03:21:33.630Z",
        "jumpUrl": "https://discord.com/channels/1485058470775623793/1499526414439944222/1499974100079214676"
      },
      {
        "authorName": "Overflow Trading Company #︱🚂choo-choo-alerts",
        "content": "@[NA]TrainAlerts \n**Living World Season 4 Train Gaming!**\nJoin us for big xp, karma, unid gear, and fun!\nR+1:45: Palawadan > GreatHall > GatheringStorms/SpecChamber\nR+3: DERVs > DBS > Incursion farm > ThunderheadKeep\nR+4: Kourna + Dragonfall metas\nFind me in Istan LFG to start or\n/sqjoin MarshAll.3528\nthe action starts <t:1777686300:R>",
        "timestamp": "2026-05-02T01:38:03.188Z",
        "jumpUrl": "https://discord.com/channels/1485058470775623793/1499526414439944222/1499948051597496464"
      },
      {
        "authorName": "Overflow Trading Company #︱🚂choo-choo-alerts",
        "content": "@[NA]TrainAlerts Bearz CMvergence (JW ALL 3) | LF ALL\n`/sqjoin Lee Ming Wei` | forming up rn , squad @ 20/50",
        "timestamp": "2026-05-01T15:15:01.212Z",
        "jumpUrl": "https://discord.com/channels/1485058470775623793/1499526414439944222/1499791260225896559"
      },
      {
        "authorName": "Overflow Trading Company #︱🚂choo-choo-alerts",
        "content": "@[NA]TrainAlerts KFC (escort) > Epooch\n`/sqjoin Lee Ming Wei` or via LFG (Inner Mayos)",
        "timestamp": "2026-05-01T12:00:51.556Z",
        "jumpUrl": "https://discord.com/channels/1485058470775623793/1499526414439944222/1499742398027403448"
      }
    ]
  }
];
